### PR TITLE
Action links per row in ListView

### PR DESCRIPTION
**Pull request by Gooliver2**
* improved action_links building
* added field_actions method
* added tests, docs

### CODE REVIEW

**Comment by Gooliver2** [comment]
@mmarcos changelog updated. 
Also I had other variant of implementation this feature. Current version suggest next format:


```
class ItemListView(ListView):
    ...
    action_links = [
        ('preview', 'staticpages:detail', 'fa-eye'),
        ('copy', 'staticpages:copy', 'fa-copy'),
        ('deactivate', 'staticpages:deactivate', 'fa-power-off'),
        ('delete', 'staticpages:delete', 'fa-trash'),
    ]
    ...
    def get_field_actions(self, obj):
        actions = [
            ('preview', 'staticpages:detail', 'fa-eye'),
            ('copy', 'staticpages:copy', 'fa-copy'),
            ('delete', 'staticpages:delete', 'fa-trash'),
        ]
        if obj.is_published:
            actions.append(
                ('deactivate', 'staticpages:deactivate', 'fa-power-off'),
            )
        else:
            actions.append(
                ('delete', 'staticpages:delete', 'fa-trash'),
            )
        return actions
```

Here we have duplicating actions and a bit ugly looking. 

Second variant to specify validation for each action:
```
class ItemListView(ListView):
    ...
    action_links = [
        ('preview', 'staticpages:detail', 'fa-eye'),
        ('copy', 'staticpages:copy', 'fa-copy'),
        ('deactivate', 'staticpages:deactivate', 'fa-power-off'),
        ('delete', 'staticpages:delete', 'fa-trash'),
    ]
    ...
    def is_deactivate_action_allowed(self, page):
        return page.is_published

    def is_delete_action_allowed(self, page):
        return not page.is_published
```
Disadvantage of such way is that if we will have a lot of actions to validate - it will be a bit difficult to go through all validation methods and handle them all, no single "entrypoint" for this. Validation and result `actions_links` is less obvious for developer.  
But no needs to duplicate actions info in two places, like we have in first variant of implementation.  

Your suggestions?

**Comment by mmarcos** [comment]
The first option is better, you can solve the duplication issue by only having the minimal `action_links` in the global settings and add the extra ones, when needed, in the `get_field_actions` method.

**Comment by Gooliver2** [comment]
@mmarcos current implementation assumes that all actions, that are not listed in `actions_links` will be skipped due to permission policy. I moved checking permission to do it once, not for each row. It will speed up `ListView`.  
So, in case we want to allow different actions per each row without restriction - I will add validation permission for each action, that are not in `actions_links` once again.

**Comment by mmarcos** [comment]
Maybe instead of adding you can only remove in `get_field_actions`:

class ItemListView(ListView):
    ...
    action_links = [
        ('preview', 'staticpages:detail', 'fa-eye'),
        ('copy', 'staticpages:copy', 'fa-copy'),
        ('deactivate', 'staticpages:deactivate', 'fa-power-off'),
        ('delete', 'staticpages:delete', 'fa-trash'),
    ]
    ...

    def get_field_actions(self, obj):
        actions = self.action_links.copy()

        if obj.is_published:
            filter(lambda a: a != ('delete', 'staticpages:delete', 'fa-trash'), actions)
        else:
            filter(lambda a: a != ('deactivate', 'staticpages:deactivate', 'fa-power-off'), actions)

        return actions

**Comment by Gooliver2** [comment]
@mmarcos interesting way! 
I'll add this behavior as suggested in docs.

**Comment by Gooliver2** [comment]
@mmarcos docs updated. 
With this approach we have one nasty thing left - if, for example, icon or name will be changed in `action_links`, but not changed in `get_field_actions` method - actions will still be available.  
But it's better then my first option, anyway,

**Comment by mmarcos** [comment]
Great, I see other reviewers in the list, but if they are optional I can merge the changes, let me know.

**Comment by Gooliver2** [comment]
@mmarcos they are optional, you can merge it.

**Pull request merged**
